basePath: /api/v1
info:
  contact: {}
  description: 测试
  license: {}
  title: 测试
  version: 0.0.1
paths:
  /api/project/create:
    post:
      description: 创建项目列表
      parameters:
      - description: 项目名称
        in: query
        name: name
        required: true
        type: string
      - description: 团队id
        in: query
        name: tid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 创建项目接口
      tags:
      - 8. CreateProject
  /api/project/dismiss:
    post:
      description: 解散项目
      parameters:
      - description: 项目id
        in: query
        name: pid
        required: true
        type: string
      - description: 团队id
        in: query
        name: tid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 解散项目接口
      tags:
      - 11. DismissProject
  /api/project/exit:
    post:
      description: 退出项目列表
      parameters:
      - description: 项目id
        in: query
        name: pid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 退出项目接口
      tags:
      - 14. ExitProject
  /api/project/join:
    post:
      description: 加入项目
      parameters:
      - description: 项目id
        in: query
        name: pid
        required: true
        type: string
      - description: 团队id
        in: query
        name: tid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 加入项目接口
      tags:
      - 9. JoinProject
  /api/project/list:
    post:
      description: 项目列表
      parameters:
      - description: 页数默认为1
        in: query
        name: page
        required: true
        type: string
      - description: 页数数量默认为20
        in: query
        name: size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 项目列表接口
      tags:
      - 10. ReadListProject
  /api/project/user:
    post:
      description: 读取项目用户列表
      parameters:
      - description: 项目id
        in: query
        name: pid
        required: true
        type: string
      - description: 页数默认为1
        in: query
        name: page
        required: true
        type: string
      - description: 页数数量默认为20
        in: query
        name: size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 读取项目用户列表接口
      tags:
      - 13. ReadListProjectUser
  /api/team/create:
    post:
      description: 创建团队
      parameters:
      - description: 团队名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 创建团队接口
      tags:
      - 1. CreateTeam
  /api/team/dismiss:
    post:
      description: 解散团队
      parameters:
      - description: 团队id
        in: query
        name: tid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 解散团队接口
      tags:
      - 4. DismissTeam
  /api/team/exit:
    post:
      description: 退出团队
      parameters:
      - description: 团队id
        in: query
        name: tid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 退出团队接口
      tags:
      - 3. ExitTeam
  /api/team/info:
    post:
      description: 查看团队信息
      parameters:
      - description: 团队id
        in: query
        name: tid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 查看团队信息接口
      tags:
      - 6. ReadInfoTeam
  /api/team/join:
    post:
      description: 加入团队
      parameters:
      - description: 团队id
        in: query
        name: tid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 加入团队接口
      tags:
      - 2. JoinTeam
  /api/team/list:
    post:
      description: 查看团队列表
      parameters:
      - description: 页数默认为1
        in: query
        name: page
        required: true
        type: string
      - description: 页数数量默认为20
        in: query
        name: size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 查看团队列表接口
      tags:
      - 5. ReadListTeam
  /api/team/user:
    post:
      description: 读取团队用户
      parameters:
      - description: 用户id
        in: query
        name: uid
        required: true
        type: string
      - description: 团队id
        in: query
        name: tid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 读取团队用户接口
      tags:
      - 8. ReadTeamUser
  /api/team/user_list:
    post:
      description: 查看团队成员列表
      parameters:
      - description: 页数默认为1
        in: query
        name: page
        required: true
        type: string
      - description: 页数数量默认为20
        in: query
        name: size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 查看团队成员列表接口
      tags:
      - 7. ReadUserListTeam
swagger: "2.0"
