basePath: /api/v1
info:
  contact: {}
  description: 测试
  license: {}
  title: 测试
  version: 0.0.1
paths:
  /api/team/create:
    post:
      description: 创建团队
      parameters:
      - description: 团队名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 创建团队接口
      tags:
      - 1.CreateTeam
swagger: "2.0"
